name: Lint Code Base

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run ESLint and output JSON results
        run: npx eslint -f json -o eslint-results.json .

      - name: Convert ESLint JSON to SARIF and upload to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.json
